# Upload data and visualize
I need to grab the beta value and the standard error (beta) for each SNP accross each cohort.

**Don't forget** I need to grab the minor allele and major allele of each SNP across each cohort. I will determine the orientation. Then, I will use a "majority rules" approach to determine if I need to flip the sign of the beta. Specifically, if the major and minor alleles are listed differently for a few cohorts, then I will need to flip the sign of the beta (i.e. change from negative to positive or vice versa.)

## Sample data
This sample data is for one variant - `rs1008078` - accross all the cohorts in meta-analysis 044. I will store the results in a dictionary. The key will be the rsID and the key will be to a pandas dataframe.

In [161]:
import os
import pandas as pd
import numpy as np


# I will create a new data frame for each variant. This data frame will have the column names:
# (1) cohort, (2) Ancestry group, (3) Beta, (4) Std. Error, (5) Seweighted, and (6) Pr(>|t|) which is the p-val
# addictionally  I will add the rows for calculating the meta in the Seweighted column and below all of the cohorts
# getting the first cohort, note that this will eventually be in a loop of the cohorts

os.chdir("C:\\Users\\jmarks\\Desktop\\Projects\\Nicotine\\GSCAN_extended_results_nicotine\\results\\results_from_missing_snp_lookup\\")
mydata = pd.ExcelFile("sample_missing_SNP_results.xlsx")
mydata = mydata.parse("Sheet1")

cohorts_list44 = ["AAND_COGEND2_AA",
"COGEND_AA",
"COGEND_EA",
"COGEND2_AA",
"COGEND2_EA",
"COPDGene_AA",
"COPDGene_EA",
"deCODE_EA",
"Dental_Caries_EA",
"EAGLE_EA",
"FINN_TWIN_EA",
"GAIN_AA",
"GAIN_EA",
"JHS_AA",
"nonGAIN_EA",
"NTR_EA",
"SAGE_AA",
"SAGE_EA",
"SNPlist",
"UW-TTURC_AA",
"UW-TTURC_EA",
"YALE_PENN_AA",
"YALE_PENN_EA"]

# add 6 rows for meta-analysis calculations
totalRows = len(cohorts_list44) + 6

# This dictionary will have an rsID for the key and the key will be to a dataframe
dataDict = {}

# initialize a dataframe
emptyArray = np.empty((totalRows,7,))
emptyArray[:] = np.nan
columns = ["SNP", "Cohort", "Ancestry group", "Beta", "Std. Error", "Seweighted", "Pr(>|t|)"]
num_of_rsIDs = len(mydata)

for rsID in range(num_of_rsIDs):
    
    # add SNP
    dataDict[markerName].iloc[rsID,0] = markerName
    
    # loop to fill in rest of dataframe and perform meta-analysis calculations
    for cohort in cohorts_list44:
        markerName = mydata.iloc[rsID,0]
        dataDict[markerName] = pd.DataFrame(columns=columns, data=emptyArray)
        
        
        # add cohort
        dataDict[markerName].iloc[rsID,]
        # add Acncestry group
        
        # add Beta
        
        # add Std. Error
        
        # add Seweighted
        
        # add p-val
    

cohort1 = mydata.filter(like=cohorts_list44[0]).iloc[0,:]
mydata.iloc[0,0]
betaVal = cohort1.filter(like=".beta")[0]
standardErr = cohort1.filter(like="sebeta")[0]
p_value = cohort1.filter(regex=".p$")[0]

#p_value

#standardErr[0]
dataDict[markerName]

          SNP  Cohort  Ancestry group  Beta  Std. Error  Seweighted  Pr(>|t|)
0   rs1008078     NaN             NaN   NaN         NaN         NaN       NaN
1         NaN     NaN             NaN   NaN         NaN         NaN       NaN
2         NaN     NaN             NaN   NaN         NaN         NaN       NaN
3         NaN     NaN             NaN   NaN         NaN         NaN       NaN
4         NaN     NaN             NaN   NaN         NaN         NaN       NaN
5         NaN     NaN             NaN   NaN         NaN         NaN       NaN
6         NaN     NaN             NaN   NaN         NaN         NaN       NaN
7         NaN     NaN             NaN   NaN         NaN         NaN       NaN
8         NaN     NaN             NaN   NaN         NaN         NaN       NaN
9         NaN     NaN             NaN   NaN         NaN         NaN       NaN
10        NaN     NaN             NaN   NaN         NaN         NaN       NaN
11        NaN     NaN             NaN   NaN         NaN         NaN       NaN
12        NaN     NaN             NaN   NaN         NaN         NaN       NaN
13        NaN     NaN             NaN   NaN         NaN         NaN       NaN
14        NaN     NaN             NaN   NaN         NaN         NaN       NaN
15        NaN     NaN             NaN   NaN         NaN         NaN       NaN
16        NaN     NaN             NaN   NaN         NaN         NaN       NaN
17        NaN     NaN             NaN   NaN         NaN         NaN       NaN
18        NaN     NaN             NaN   NaN         NaN         NaN       NaN
19        NaN     NaN             NaN   NaN         NaN         NaN       NaN
20        NaN     NaN             NaN   NaN         NaN         NaN       NaN
21        NaN     NaN             NaN   NaN         NaN         NaN       NaN
22        NaN     NaN             NaN   NaN         NaN         NaN       NaN
23        NaN     NaN             NaN   NaN         NaN         NaN       NaN
24        NaN     NaN             NaN   NaN         NaN         NaN       NaN
25        NaN     NaN             NaN   NaN         NaN         NaN       NaN
26        NaN     NaN             NaN   NaN         NaN         NaN       NaN
27        NaN     NaN             NaN   NaN         NaN         NaN       NaN
28        NaN     NaN             NaN   NaN         NaN         NaN       NaN

In [150]:
import numpy as np
a = np.empty((29,7,))
a[:] = np.nan
print(a)
tempDF = pd.DataFrame(np.nan, index=[0,1,2,3],columns=["a","b","c"])
#tempDF

[[ nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan]]

In [112]:
dataDict['rs1008078']

Empty DataFrame
Columns: [SNP, Cohort, Ancestry group, Beta, Std. Error, Seweighted, Pr(>|t|)]
Index: []

# 044 meta-analysis

In [51]:
import os
import pandas as pd



os.chdir("C:\\Users\\jmarks\\Desktop\\Projects\\Nicotine\\GSCAN_extended_results_nicotine\\results\\results_from_missing_snp_lookup\\")


#os.listdir()
#xl = pd.ExcelFile("missing_SNPs_results_prefiltered_meta_analyses_044_045_046_V02.xlsx")
xl.sheet_names
zero44 = xl.sheet_names[0]
zero44 = xl.parse(zero44)
zero45 = xl.sheet_names[1]
zero45 = xl.parse(zero45)
zero46 = xl.sheet_names[2]
zero46 = xl.parse(zero46)
zero44.iloc[0:1,:]

# beta is in each, but also sebeta is too.

IndexError: list index out of range

# 045 meta-analysis

# 046 meta-analysis